# task config
task: multiwaypoint

# simulation config
sim_freq: 60
agent_interaction_steps: 12 # step 0.2s
randomise_waypoint_sequence: True

# termination config
max_steps: 2500             # episode length: maxsteps *  0.2s = 500s
altitude_limit: 2500
acceleration_limit_x: 10.0
acceleration_limit_y: 10.0
acceleration_limit_z: 10.0

# aircraft config
aircraft_configs: {
  A0100: {
    color: Red,
    model: f16,
    max_heading_increment: 180,       # degree
    max_altitude_increment: 7000,     # feet
    max_velocities_u_increment: 100,  # meter
    check_interval: 30,               # second
    init_state: {
      ic_long_gc_deg: 120.0,
      ic_lat_geod_deg: 60.0,
      ic_h_sl_ft: 20000,
      ic_psi_true_deg: 0.0,
      ic_u_fps: 800.0,
    }
  }
}

# success radius
success_radius: 750  # m - realistic for high-speed F-16 navigation

# waypoint config
waypoint_configs:
  100000001:
    color: Blue
    type: Navaid+Static+Waypoint
    model: Waypoint
    init_state:
      waypoint/longitude-geod-deg: 119.54
      waypoint/latitude-geod-deg: 60.0
      waypoint/altitude-ft: 15000
      waypoint/active: 0
  100000002:
    color: Blue
    type: Navaid+Static+Waypoint
    model: Waypoint
    init_state:
      waypoint/longitude-geod-deg: 120.38
      waypoint/latitude-geod-deg: 60.00
      waypoint/altitude-ft: 15000
      waypoint/active: 0
  100000003:
    color: Blue
    type: Navaid+Static+Waypoint
    model: Waypoint
    init_state:
      waypoint/longitude-geod-deg: 120.0
      waypoint/latitude-geod-deg: 59.8
      waypoint/altitude-ft: 15000
      waypoint/active: 0



# (longitude, latitude, altitude)
battle_field_center: [120.0, 60.0, 0.0]

# battle field corners
corners_coordinates: [
  [119.1015, 59.5505, 0.0],
  [120.8985, 59.5505, 0.0],
  [120.8985, 60.4495, 0.0],
  [119.1015, 60.4495, 0.0]
]
## --> this is about a 100km x 100km area

# reward config
AltitudeReward_safe_altitude: 4.0
AltitudeReward_danger_altitude: 3.5
AltitudeReward_Kv: 0.2
